
class EQUIPMENT_ADDRESS():
    SCOPE = "10.126.111.36"
    
    AC_SOURCE = 5
    
    
    
    POWER_METER_DIM = 21
    
    SIG_GEN = '11'
    
    ELOAD = 8

    POWER_METER_SOURCE = 30
    POWER_METER_LOAD_1 = 2
    POWER_METER_LOAD_2 = 10
    POWER_METER_LOAD_3 = 25
    POWER_METER_LOAD_4 = 6

    ELOAD_CHANNEL_1 = 1
    ELOAD_CHANNEL_2 = 3
    ELOAD_CHANNEL_3 = 5
    ELOAD_CHANNEL_4 = 7

    DC_SOURCE_DIMMER = 4



    # LSCOPE = "169.254.94.235"
    # SCOPE = "10.126.111.35"
    
    # AC_SOURCE = 5
    
    # POWER_METER_SOURCE = 11
    # POWER_METER_LOAD_1 = 1
    # POWER_METER_LOAD_2 = 1
    # POWER_METER_DIM = 21
    
    # SIG_GEN = '11'
    
    # ELOAD = 8
    # ELOAD_CHANNEL = 7

    # ARDUINO_COMM_PORT = 5