# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'automation_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.




# # COMMS
# ac_source_address = 5
# # source_power_meter_address = 1
# # load_power_meter_address = 2
# # eload_address = 8
# # scope_address = "10.125.10.148"
# # scope2_address = "10.125.10.227"

# """IMPORT DEPENDENCIES"""
# import sys
# import pyautogui
# from time import sleep, time
# from powi.equipment import ACSource, PowerMeter, ElectronicLoad, Oscilloscope
# from powi.equipment import headers, create_folder, footers, waveform_counter, soak, convert_argv_to_int_list
# from time import sleep, time
# import os
# waveform_counter = 0

# """INITIALIZE EQUIPMENT"""
# # ac = ACSource(ac_source_address)
# # pms = PowerMeter(source_power_meter_address)
# # pml = PowerMeter(load_power_meter_address)
# # eload = ElectronicLoad(eload_address)
# # scope = Oscilloscope(scope_address)
# # scope2 = Oscilloscope(scope2_address)












from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def __init__(self):
        
        import sys
        import pyautogui
        from time import sleep, time
        from powi.equipment import ACSource, PowerMeter, ElectronicLoad, Oscilloscope
        from powi.equipment import headers, create_folder, footers, waveform_counter, soak, convert_argv_to_int_list
        from time import sleep, time
        import os
        waveform_counter = 0
        ac_source_address = 5

        # self.ac = ACSource(ac_source_address)
        # self.ac.voltage = 300
        # self.ac.frequency = 60


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 76)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(10, 10, 438, 23))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        
        self.comms = QtWidgets.QToolButton(self.splitter)
        self.comms.setObjectName("comms")

        self.input_voltage_label = QtWidgets.QLabel(self.splitter)
        self.input_voltage_label.setObjectName("input_voltage_label")

        self.input_voltage = QtWidgets.QLineEdit(self.splitter)
        self.input_voltage.setObjectName("input_voltage")
        
        self.input_type = QtWidgets.QComboBox(self.splitter)
        self.input_type.setObjectName("input_type")
        self.input_type.addItem("")
        self.input_type.addItem("")
        
        self.AC_ON = QtWidgets.QPushButton(self.splitter)
        self.AC_ON.setObjectName("AC_ON")
        self.AC_ON.clicked.connect(self.ac_turn_on)

        self.AC_OFF = QtWidgets.QPushButton(self.splitter)
        self.AC_OFF.setObjectName("AC_OFF")
        self.AC_OFF.clicked.connect(self.ac_turn_off)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 470, 21))
        
        self.menubar.setObjectName("menubar")
        self.menuAC_Gui = QtWidgets.QMenu(self.menubar)
        
        self.menuAC_Gui.setObjectName("menuAC_Gui")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuAC_Gui.addSeparator()
        self.menubar.addAction(self.menuAC_Gui.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comms.setText(_translate("MainWindow", "COMMS"))
        self.input_voltage_label.setText(_translate("MainWindow", "Input Voltage"))
        self.input_voltage.setText(_translate("MainWindow", "120"))
        self.input_type.setItemText(0, _translate("MainWindow", "AC"))
        self.input_type.setItemText(1, _translate("MainWindow", "DC"))
        self.AC_ON.setText(_translate("MainWindow", "ON"))
        self.AC_OFF.setText(_translate("MainWindow", "OFF"))
        self.menuAC_Gui.setTitle(_translate("MainWindow", "AC Gui"))



class functions(Ui_MainWindow):


    

    def ac_turn_on(self):
        vin = float(self.input_voltage.text())
        if vin >= 180 or vin <= 265: freq = 50
        else: freq = 60

        # print(vin)
        # print(freq)
        # self.ac.turn_on()
        print("AC turn on.")
        # print(type(self.input_voltage.text()))
        # print(type(self.input_type.currentText()))
        # self.ac.voltage = vin
        # self.ac.frequency = freq
        # self.ac.turn_on()

    def ac_turn_off(self):
        # self.ac.turn_off()
        print("AC turn off.")
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = functions()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
