# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui_2lHJfix.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import logo_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1372, 893)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.date_label = QLabel(self.centralwidget)
        self.date_label.setObjectName(u"date_label")
        self.date_label.setGeometry(QRect(1260, 850, 101, 21))
        self.logo_label = QLabel(self.centralwidget)
        self.logo_label.setObjectName(u"logo_label")
        self.logo_label.setGeometry(QRect(1160, 780, 201, 71))
        self.logo_label.setStyleSheet(u"")
        self.logo_label.setPixmap(QPixmap(u":/logo/pi-logo.png"))
        self.logo_label.setScaledContents(True)
        self.led_control = QGroupBox(self.centralwidget)
        self.led_control.setObjectName(u"led_control")
        self.led_control.setGeometry(QRect(690, 10, 271, 181))
        self.led_load_46V_button = QPushButton(self.led_control)
        self.led_load_46V_button.setObjectName(u"led_load_46V_button")
        self.led_load_46V_button.setGeometry(QRect(10, 20, 101, 31))
        self.led_load_36V_button = QPushButton(self.led_control)
        self.led_load_36V_button.setObjectName(u"led_load_36V_button")
        self.led_load_36V_button.setGeometry(QRect(10, 60, 101, 31))
        self.led_load_24V_button = QPushButton(self.led_control)
        self.led_load_24V_button.setObjectName(u"led_load_24V_button")
        self.led_load_24V_button.setGeometry(QRect(10, 100, 101, 31))
        self.led_load_NL_button = QPushButton(self.led_control)
        self.led_load_NL_button.setObjectName(u"led_load_NL_button")
        self.led_load_NL_button.setGeometry(QRect(10, 140, 101, 31))
        self.discharge_output_button = QPushButton(self.led_control)
        self.discharge_output_button.setObjectName(u"discharge_output_button")
        self.discharge_output_button.setGeometry(QRect(120, 20, 141, 151))
        self.discharge_output_button.setStyleSheet(u"")
        self.ac_control = QGroupBox(self.centralwidget)
        self.ac_control.setObjectName(u"ac_control")
        self.ac_control.setGeometry(QRect(10, 10, 371, 81))
        self.vin_label = QLabel(self.ac_control)
        self.vin_label.setObjectName(u"vin_label")
        self.vin_label.setGeometry(QRect(10, 30, 41, 21))
        self.ac_input_voltage_textbox = QLineEdit(self.ac_control)
        self.ac_input_voltage_textbox.setObjectName(u"ac_input_voltage_textbox")
        self.ac_input_voltage_textbox.setGeometry(QRect(50, 30, 31, 21))
        self.ac_input_voltage_textbox.setLayoutDirection(Qt.LeftToRight)
        self.ac_on_button = QPushButton(self.ac_control)
        self.ac_on_button.setObjectName(u"ac_on_button")
        self.ac_on_button.setGeometry(QRect(180, 20, 81, 41))
        palette = QPalette()
        brush = QBrush(QColor(85, 170, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        self.ac_on_button.setPalette(palette)
        self.ac_off_button = QPushButton(self.ac_control)
        self.ac_off_button.setObjectName(u"ac_off_button")
        self.ac_off_button.setGeometry(QRect(270, 20, 81, 41))
        self.coupling_type_button = QComboBox(self.ac_control)
        self.coupling_type_button.addItem("")
        self.coupling_type_button.addItem("")
        self.coupling_type_button.setObjectName(u"coupling_type_button")
        self.coupling_type_button.setGeometry(QRect(90, 30, 41, 22))
        self.eload_control = QGroupBox(self.centralwidget)
        self.eload_control.setObjectName(u"eload_control")
        self.eload_control.setGeometry(QRect(390, 10, 291, 181))
        self.comms_box = QGroupBox(self.centralwidget)
        self.comms_box.setObjectName(u"comms_box")
        self.comms_box.setGeometry(QRect(970, 10, 311, 181))
        self.comms_ac_button = QPushButton(self.comms_box)
        self.comms_ac_button.setObjectName(u"comms_ac_button")
        self.comms_ac_button.setGeometry(QRect(180, 30, 101, 23))
        self.eload_address_textbox = QLineEdit(self.comms_box)
        self.eload_address_textbox.setObjectName(u"eload_address_textbox")
        self.eload_address_textbox.setGeometry(QRect(90, 60, 81, 20))
        self.eload_address_textbox.setAlignment(Qt.AlignCenter)
        self.comms_eload_button = QPushButton(self.comms_box)
        self.comms_eload_button.setObjectName(u"comms_eload_button")
        self.comms_eload_button.setGeometry(QRect(180, 60, 101, 23))
        self.ac_address_label = QLabel(self.comms_box)
        self.ac_address_label.setObjectName(u"ac_address_label")
        self.ac_address_label.setGeometry(QRect(60, 30, 31, 21))
        self.comms_scope_button = QPushButton(self.comms_box)
        self.comms_scope_button.setObjectName(u"comms_scope_button")
        self.comms_scope_button.setGeometry(QRect(180, 90, 101, 23))
        self.eload_address_label = QLabel(self.comms_box)
        self.eload_address_label.setObjectName(u"eload_address_label")
        self.eload_address_label.setGeometry(QRect(50, 60, 41, 21))
        self.scope_address_textbox = QLineEdit(self.comms_box)
        self.scope_address_textbox.setObjectName(u"scope_address_textbox")
        self.scope_address_textbox.setGeometry(QRect(90, 90, 81, 20))
        self.scope_address_textbox.setAlignment(Qt.AlignCenter)
        self.scope_address_label = QLabel(self.comms_box)
        self.scope_address_label.setObjectName(u"scope_address_label")
        self.scope_address_label.setGeometry(QRect(50, 90, 41, 21))
        self.ac_address_textbox = QLineEdit(self.comms_box)
        self.ac_address_textbox.setObjectName(u"ac_address_textbox")
        self.ac_address_textbox.setGeometry(QRect(90, 30, 81, 20))
        self.ac_address_textbox.setAlignment(Qt.AlignCenter)
        self.led_address_label = QLabel(self.comms_box)
        self.led_address_label.setObjectName(u"led_address_label")
        self.led_address_label.setGeometry(QRect(50, 120, 41, 21))
        self.comms_led_button = QPushButton(self.comms_box)
        self.comms_led_button.setObjectName(u"comms_led_button")
        self.comms_led_button.setGeometry(QRect(180, 120, 101, 23))
        self.scope_control = QGroupBox(self.centralwidget)
        self.scope_control.setObjectName(u"scope_control")
        self.scope_control.setGeometry(QRect(10, 200, 781, 241))
        self.time_scale_textbox_2 = QLineEdit(self.scope_control)
        self.time_scale_textbox_2.setObjectName(u"time_scale_textbox_2")
        self.time_scale_textbox_2.setGeometry(QRect(110, 100, 50, 25))
        self.time_position_textbox = QLineEdit(self.scope_control)
        self.time_position_textbox.setObjectName(u"time_position_textbox")
        self.time_position_textbox.setGeometry(QRect(110, 40, 50, 25))
        self.time_scale_label = QLabel(self.scope_control)
        self.time_scale_label.setObjectName(u"time_scale_label")
        self.time_scale_label.setGeometry(QRect(20, 70, 81, 25))
        self.time_scale_label_2 = QLabel(self.scope_control)
        self.time_scale_label_2.setObjectName(u"time_scale_label_2")
        self.time_scale_label_2.setGeometry(QRect(20, 100, 91, 25))
        self.time_scale_textbox = QLineEdit(self.scope_control)
        self.time_scale_textbox.setObjectName(u"time_scale_textbox")
        self.time_scale_textbox.setGeometry(QRect(110, 70, 50, 25))
        self.time_postion_label = QLabel(self.scope_control)
        self.time_postion_label.setObjectName(u"time_postion_label")
        self.time_postion_label.setGeometry(QRect(20, 40, 81, 25))
        self.trigger_type_combobox = QComboBox(self.scope_control)
        self.trigger_type_combobox.addItem("")
        self.trigger_type_combobox.addItem("")
        self.trigger_type_combobox.addItem("")
        self.trigger_type_combobox.setObjectName(u"trigger_type_combobox")
        self.trigger_type_combobox.setGeometry(QRect(400, 20, 61, 22))
        self.filename_label = QLabel(self.scope_control)
        self.filename_label.setObjectName(u"filename_label")
        self.filename_label.setGeometry(QRect(340, 180, 71, 21))
        self.trigger_edge_combobox = QComboBox(self.scope_control)
        self.trigger_edge_combobox.addItem("")
        self.trigger_edge_combobox.addItem("")
        self.trigger_edge_combobox.addItem("")
        self.trigger_edge_combobox.setObjectName(u"trigger_edge_combobox")
        self.trigger_edge_combobox.setGeometry(QRect(400, 50, 61, 22))
        self.folder_path_label = QLabel(self.scope_control)
        self.folder_path_label.setObjectName(u"folder_path_label")
        self.folder_path_label.setGeometry(QRect(340, 210, 71, 21))
        self.scope_single_button = QPushButton(self.scope_control)
        self.scope_single_button.setObjectName(u"scope_single_button")
        self.scope_single_button.setGeometry(QRect(490, 60, 75, 71))
        self.screenshot_button = QPushButton(self.scope_control)
        self.screenshot_button.setObjectName(u"screenshot_button")
        self.screenshot_button.setGeometry(QRect(650, 60, 121, 71))
        self.screenshot_button.setStyleSheet(u"QPushButton {url(:/logo/screenshot-logo.png)}")
        self.screenshot_button.setFlat(False)
        self.folder_path_textbox = QLineEdit(self.scope_control)
        self.folder_path_textbox.setObjectName(u"folder_path_textbox")
        self.folder_path_textbox.setGeometry(QRect(410, 210, 331, 21))
        self.trigger_channel_combobox = QComboBox(self.scope_control)
        self.trigger_channel_combobox.addItem("")
        self.trigger_channel_combobox.addItem("")
        self.trigger_channel_combobox.addItem("")
        self.trigger_channel_combobox.addItem("")
        self.trigger_channel_combobox.setObjectName(u"trigger_channel_combobox")
        self.trigger_channel_combobox.setGeometry(QRect(400, 80, 61, 22))
        self.norm_button = QPushButton(self.scope_control)
        self.norm_button.setObjectName(u"norm_button")
        self.norm_button.setGeometry(QRect(570, 20, 71, 31))
        self.scope_run_stop_button = QPushButton(self.scope_control)
        self.scope_run_stop_button.setObjectName(u"scope_run_stop_button")
        self.scope_run_stop_button.setGeometry(QRect(570, 60, 75, 71))
        self.scope_run_stop_button.setStyleSheet(u"QPushButton { background-color: rgb(255, 101, 104);\n"
"}")
        self.trigger_level_label = QLabel(self.scope_control)
        self.trigger_level_label.setObjectName(u"trigger_level_label")
        self.trigger_level_label.setGeometry(QRect(310, 110, 71, 16))
        self.trigger_type_label = QLabel(self.scope_control)
        self.trigger_type_label.setObjectName(u"trigger_type_label")
        self.trigger_type_label.setGeometry(QRect(310, 20, 71, 21))
        self.foldername_textbox = QLineEdit(self.scope_control)
        self.foldername_textbox.setObjectName(u"foldername_textbox")
        self.foldername_textbox.setGeometry(QRect(410, 150, 121, 21))
        self.filename_textbox = QLineEdit(self.scope_control)
        self.filename_textbox.setObjectName(u"filename_textbox")
        self.filename_textbox.setGeometry(QRect(410, 180, 121, 21))
        self.trigger_channel_label = QLabel(self.scope_control)
        self.trigger_channel_label.setObjectName(u"trigger_channel_label")
        self.trigger_channel_label.setGeometry(QRect(310, 80, 81, 16))
        self.trigger_edge_label = QLabel(self.scope_control)
        self.trigger_edge_label.setObjectName(u"trigger_edge_label")
        self.trigger_edge_label.setGeometry(QRect(310, 50, 81, 20))
        self.trigger_level_textbox = QLineEdit(self.scope_control)
        self.trigger_level_textbox.setObjectName(u"trigger_level_textbox")
        self.trigger_level_textbox.setGeometry(QRect(400, 110, 51, 20))
        self.foldername_label = QLabel(self.scope_control)
        self.foldername_label.setObjectName(u"foldername_label")
        self.foldername_label.setGeometry(QRect(340, 150, 71, 21))
        self.auto_button = QPushButton(self.scope_control)
        self.auto_button.setObjectName(u"auto_button")
        self.auto_button.setGeometry(QRect(490, 20, 71, 31))
        self.label_9 = QLabel(self.scope_control)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(170, 40, 21, 25))
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_10 = QLabel(self.scope_control)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(170, 70, 31, 25))
        self.label_10.setAlignment(Qt.AlignCenter)
        self.pushButton = QPushButton(self.scope_control)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(170, 100, 41, 25))
        self.label_11 = QLabel(self.scope_control)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(450, 110, 21, 21))
        self.label_11.setAlignment(Qt.AlignCenter)
        self.setting = QToolButton(self.centralwidget)
        self.setting.setObjectName(u"setting")
        self.setting.setGeometry(QRect(1020, 330, 25, 21))
        self.ch_rel_y_label = QLabel(self.centralwidget)
        self.ch_rel_y_label.setObjectName(u"ch_rel_y_label")
        self.ch_rel_y_label.setGeometry(QRect(410, 580, 31, 25))
        self.ch_rel_x_textbox = QLineEdit(self.centralwidget)
        self.ch_rel_x_textbox.setObjectName(u"ch_rel_x_textbox")
        self.ch_rel_x_textbox.setGeometry(QRect(380, 580, 21, 25))
        self.ch_rel_x_textbox.setAlignment(Qt.AlignCenter)
        self.ch_offset_label = QLabel(self.centralwidget)
        self.ch_offset_label.setObjectName(u"ch_offset_label")
        self.ch_offset_label.setGeometry(QRect(350, 610, 51, 25))
        self.ch_offset_textbox = QLineEdit(self.centralwidget)
        self.ch_offset_textbox.setObjectName(u"ch_offset_textbox")
        self.ch_offset_textbox.setGeometry(QRect(400, 610, 31, 25))
        self.ch_offset_textbox.setAlignment(Qt.AlignCenter)
        self.ch_coupling_label = QLabel(self.centralwidget)
        self.ch_coupling_label.setObjectName(u"ch_coupling_label")
        self.ch_coupling_label.setGeometry(QRect(200, 610, 41, 25))
        self.ch_bandwidth_unit = QLabel(self.centralwidget)
        self.ch_bandwidth_unit.setObjectName(u"ch_bandwidth_unit")
        self.ch_bandwidth_unit.setGeometry(QRect(300, 580, 31, 25))
        self.ch_coupling_combobox = QComboBox(self.centralwidget)
        self.ch_coupling_combobox.addItem("")
        self.ch_coupling_combobox.addItem("")
        self.ch_coupling_combobox.addItem("")
        self.ch_coupling_combobox.setObjectName(u"ch_coupling_combobox")
        self.ch_coupling_combobox.setGeometry(QRect(240, 610, 81, 25))
        self.scope_channel_1_enable_button = QPushButton(self.centralwidget)
        self.scope_channel_1_enable_button.setObjectName(u"scope_channel_1_enable_button")
        self.scope_channel_1_enable_button.setGeometry(QRect(50, 500, 141, 131))
        self.ch_rel_y_textbox = QLineEdit(self.centralwidget)
        self.ch_rel_y_textbox.setObjectName(u"ch_rel_y_textbox")
        self.ch_rel_y_textbox.setGeometry(QRect(440, 580, 21, 25))
        self.ch_rel_y_textbox.setAlignment(Qt.AlignCenter)
        self.invert_button = QPushButton(self.centralwidget)
        self.invert_button.setObjectName(u"invert_button")
        self.invert_button.setGeometry(QRect(320, 490, 61, 25))
        self.ch_color_combobox = QComboBox(self.centralwidget)
        self.ch_color_combobox.addItem("")
        self.ch_color_combobox.addItem("")
        self.ch_color_combobox.addItem("")
        self.ch_color_combobox.addItem("")
        self.ch_color_combobox.addItem("")
        self.ch_color_combobox.addItem("")
        self.ch_color_combobox.setObjectName(u"ch_color_combobox")
        self.ch_color_combobox.setGeometry(QRect(390, 520, 71, 25))
        self.ch_scale_textbox = QLineEdit(self.centralwidget)
        self.ch_scale_textbox.setObjectName(u"ch_scale_textbox")
        self.ch_scale_textbox.setGeometry(QRect(240, 520, 51, 25))
        self.ch_scale_textbox.setAlignment(Qt.AlignCenter)
        self.ch_color_label = QLabel(self.centralwidget)
        self.ch_color_label.setObjectName(u"ch_color_label")
        self.ch_color_label.setGeometry(QRect(350, 520, 41, 25))
        self.ch_position_textbox = QLineEdit(self.centralwidget)
        self.ch_position_textbox.setObjectName(u"ch_position_textbox")
        self.ch_position_textbox.setGeometry(QRect(240, 550, 51, 25))
        self.ch_position_textbox.setAlignment(Qt.AlignCenter)
        self.ch_label_textbox = QLineEdit(self.centralwidget)
        self.ch_label_textbox.setObjectName(u"ch_label_textbox")
        self.ch_label_textbox.setGeometry(QRect(390, 550, 111, 25))
        self.ch_label_textbox.setAlignment(Qt.AlignCenter)
        self.ch_label_label = QLabel(self.centralwidget)
        self.ch_label_label.setObjectName(u"ch_label_label")
        self.ch_label_label.setGeometry(QRect(350, 550, 41, 25))
        self.ch_bandwidth_label = QLabel(self.centralwidget)
        self.ch_bandwidth_label.setObjectName(u"ch_bandwidth_label")
        self.ch_bandwidth_label.setGeometry(QRect(200, 580, 41, 25))
        self.autozero_button = QPushButton(self.centralwidget)
        self.autozero_button.setObjectName(u"autozero_button")
        self.autozero_button.setGeometry(QRect(390, 490, 71, 25))
        self.ch_scale_label = QLabel(self.centralwidget)
        self.ch_scale_label.setObjectName(u"ch_scale_label")
        self.ch_scale_label.setGeometry(QRect(200, 520, 41, 25))
        self.ch_rel_x_label = QLabel(self.centralwidget)
        self.ch_rel_x_label.setObjectName(u"ch_rel_x_label")
        self.ch_rel_x_label.setGeometry(QRect(350, 580, 31, 25))
        self.ch_position_label = QLabel(self.centralwidget)
        self.ch_position_label.setObjectName(u"ch_position_label")
        self.ch_position_label.setGeometry(QRect(200, 550, 41, 25))
        self.ch_bandwidth_combobox = QComboBox(self.centralwidget)
        self.ch_bandwidth_combobox.addItem("")
        self.ch_bandwidth_combobox.addItem("")
        self.ch_bandwidth_combobox.addItem("")
        self.ch_bandwidth_combobox.setObjectName(u"ch_bandwidth_combobox")
        self.ch_bandwidth_combobox.setGeometry(QRect(240, 580, 51, 25))
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(920, 220, 91, 81))
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(1040, 220, 41, 22))
        self.comboBox_2 = QComboBox(self.centralwidget)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(1090, 220, 81, 22))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(1020, 250, 21, 21))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(1020, 280, 21, 21))
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(1040, 250, 51, 20))
        self.lineEdit_2 = QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(1040, 280, 51, 20))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(1100, 280, 21, 21))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(1100, 250, 21, 21))
        self.lineEdit_3 = QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(1120, 250, 51, 20))
        self.lineEdit_4 = QLineEdit(self.centralwidget)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(1120, 280, 51, 20))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(1020, 220, 21, 21))
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(920, 330, 91, 21))
        self.ch_color_label_2 = QLabel(self.centralwidget)
        self.ch_color_label_2.setObjectName(u"ch_color_label_2")
        self.ch_color_label_2.setGeometry(QRect(200, 490, 41, 25))
        self.ch_color_combobox_2 = QComboBox(self.centralwidget)
        self.ch_color_combobox_2.addItem("")
        self.ch_color_combobox_2.addItem("")
        self.ch_color_combobox_2.setObjectName(u"ch_color_combobox_2")
        self.ch_color_combobox_2.setGeometry(QRect(240, 490, 71, 25))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(300, 520, 31, 25))
        self.label_6.setLayoutDirection(Qt.LeftToRight)
        self.label_6.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(300, 550, 31, 25))
        self.label_7.setLayoutDirection(Qt.LeftToRight)
        self.label_7.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(435, 610, 21, 25))
        self.label_8.setLayoutDirection(Qt.LeftToRight)
        self.label_8.setAlignment(Qt.AlignCenter)
        self.lineEdit_5 = QLineEdit(self.centralwidget)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(1030, 590, 81, 21))
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(980, 590, 51, 21))
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(980, 620, 51, 21))
        self.label_13.setAlignment(Qt.AlignCenter)
        self.lineEdit_6 = QLineEdit(self.centralwidget)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(1030, 620, 81, 21))
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(980, 650, 51, 21))
        self.label_14.setAlignment(Qt.AlignCenter)
        self.lineEdit_7 = QLineEdit(self.centralwidget)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(1030, 650, 81, 21))
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(990, 680, 75, 23))
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(1070, 680, 75, 23))
        self.eload_iout_textbox_1 = QLineEdit(self.centralwidget)
        self.eload_iout_textbox_1.setObjectName(u"eload_iout_textbox_1")
        self.eload_iout_textbox_1.setGeometry(QRect(1040, 520, 61, 20))
        self.eload_enable_button = QPushButton(self.centralwidget)
        self.eload_enable_button.setObjectName(u"eload_enable_button")
        self.eload_enable_button.setGeometry(QRect(1110, 420, 81, 51))
        self.eload_enable_button.setAutoFillBackground(False)
        self.eload_enable_button.setStyleSheet(u"QPushButton { background-color: rgb(255, 101, 104);\n"
"}")
        self.eload_channel_label = QLabel(self.centralwidget)
        self.eload_channel_label.setObjectName(u"eload_channel_label")
        self.eload_channel_label.setGeometry(QRect(990, 420, 51, 20))
        self.eload_channel_label.setAlignment(Qt.AlignCenter)
        self.eload_mode_label = QLabel(self.centralwidget)
        self.eload_mode_label.setObjectName(u"eload_mode_label")
        self.eload_mode_label.setGeometry(QRect(990, 450, 51, 20))
        self.eload_mode_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.eload_iout_unit_label_1 = QLabel(self.centralwidget)
        self.eload_iout_unit_label_1.setObjectName(u"eload_iout_unit_label_1")
        self.eload_iout_unit_label_1.setGeometry(QRect(1110, 520, 51, 20))
        self.eload_iout_label = QLabel(self.centralwidget)
        self.eload_iout_label.setObjectName(u"eload_iout_label")
        self.eload_iout_label.setGeometry(QRect(990, 490, 51, 20))
        self.eload_iout_textbox = QLineEdit(self.centralwidget)
        self.eload_iout_textbox.setObjectName(u"eload_iout_textbox")
        self.eload_iout_textbox.setGeometry(QRect(1040, 490, 61, 20))
        self.eload_iout_label_1 = QLabel(self.centralwidget)
        self.eload_iout_label_1.setObjectName(u"eload_iout_label_1")
        self.eload_iout_label_1.setGeometry(QRect(990, 520, 51, 20))
        self.eload_iout_unit_label = QLabel(self.centralwidget)
        self.eload_iout_unit_label.setObjectName(u"eload_iout_unit_label")
        self.eload_iout_unit_label.setGeometry(QRect(1110, 490, 51, 20))
        self.eload_channel_combobox = QComboBox(self.centralwidget)
        self.eload_channel_combobox.addItem("")
        self.eload_channel_combobox.addItem("")
        self.eload_channel_combobox.addItem("")
        self.eload_channel_combobox.addItem("")
        self.eload_channel_combobox.addItem("")
        self.eload_channel_combobox.addItem("")
        self.eload_channel_combobox.addItem("")
        self.eload_channel_combobox.addItem("")
        self.eload_channel_combobox.setObjectName(u"eload_channel_combobox")
        self.eload_channel_combobox.setGeometry(QRect(1040, 420, 51, 22))
        self.eload_mode_combobox = QComboBox(self.centralwidget)
        self.eload_mode_combobox.addItem("")
        self.eload_mode_combobox.addItem("")
        self.eload_mode_combobox.addItem("")
        self.eload_mode_combobox.addItem("")
        self.eload_mode_combobox.addItem("")
        self.eload_mode_combobox.addItem("")
        self.eload_mode_combobox.addItem("")
        self.eload_mode_combobox.addItem("")
        self.eload_mode_combobox.addItem("")
        self.eload_mode_combobox.addItem("")
        self.eload_mode_combobox.addItem("")
        self.eload_mode_combobox.setObjectName(u"eload_mode_combobox")
        self.eload_mode_combobox.setGeometry(QRect(1040, 450, 51, 22))
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(990, 570, 121, 16))
        self.eload_iout_unit_label_2 = QLabel(self.centralwidget)
        self.eload_iout_unit_label_2.setObjectName(u"eload_iout_unit_label_2")
        self.eload_iout_unit_label_2.setGeometry(QRect(1120, 590, 51, 20))
        self.eload_iout_unit_label_3 = QLabel(self.centralwidget)
        self.eload_iout_unit_label_3.setObjectName(u"eload_iout_unit_label_3")
        self.eload_iout_unit_label_3.setGeometry(QRect(1120, 620, 51, 20))
        self.eload_iout_unit_label_4 = QLabel(self.centralwidget)
        self.eload_iout_unit_label_4.setObjectName(u"eload_iout_unit_label_4")
        self.eload_iout_unit_label_4.setGeometry(QRect(1120, 650, 51, 20))
        self.measure_button = QPushButton(self.centralwidget)
        self.measure_button.setObjectName(u"measure_button")
        self.measure_button.setGeometry(QRect(470, 490, 71, 25))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.trigger_level_textbox, self.trigger_channel_combobox)
        QWidget.setTabOrder(self.trigger_channel_combobox, self.scope_run_stop_button)
        QWidget.setTabOrder(self.scope_run_stop_button, self.scope_single_button)
        QWidget.setTabOrder(self.scope_single_button, self.ac_input_voltage_textbox)
        QWidget.setTabOrder(self.ac_input_voltage_textbox, self.ac_on_button)
        QWidget.setTabOrder(self.ac_on_button, self.ac_off_button)
        QWidget.setTabOrder(self.ac_off_button, self.screenshot_button)
        QWidget.setTabOrder(self.screenshot_button, self.trigger_edge_combobox)
        QWidget.setTabOrder(self.trigger_edge_combobox, self.filename_textbox)
        QWidget.setTabOrder(self.filename_textbox, self.auto_button)
        QWidget.setTabOrder(self.auto_button, self.norm_button)
        QWidget.setTabOrder(self.norm_button, self.led_load_46V_button)
        QWidget.setTabOrder(self.led_load_46V_button, self.led_load_36V_button)
        QWidget.setTabOrder(self.led_load_36V_button, self.led_load_24V_button)
        QWidget.setTabOrder(self.led_load_24V_button, self.led_load_NL_button)
        QWidget.setTabOrder(self.led_load_NL_button, self.discharge_output_button)
        QWidget.setTabOrder(self.discharge_output_button, self.folder_path_textbox)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.date_label.setText(QCoreApplication.translate("MainWindow", u"Date: 22-Sep-2022", None))
        self.logo_label.setText("")
        self.led_control.setTitle(QCoreApplication.translate("MainWindow", u"LED Load Control", None))
        self.led_load_46V_button.setText(QCoreApplication.translate("MainWindow", u"46V LED", None))
        self.led_load_36V_button.setText(QCoreApplication.translate("MainWindow", u"36V LED", None))
        self.led_load_24V_button.setText(QCoreApplication.translate("MainWindow", u"24V LED", None))
        self.led_load_NL_button.setText(QCoreApplication.translate("MainWindow", u"NO LOAD", None))
        self.discharge_output_button.setText(QCoreApplication.translate("MainWindow", u"DISCHARGE OUTPUT", None))
        self.ac_control.setTitle(QCoreApplication.translate("MainWindow", u"AC Control", None))
        self.vin_label.setText(QCoreApplication.translate("MainWindow", u"Vin", None))
        self.ac_input_voltage_textbox.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.ac_on_button.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.ac_off_button.setText(QCoreApplication.translate("MainWindow", u"OFF", None))
        self.coupling_type_button.setItemText(0, QCoreApplication.translate("MainWindow", u"AC", None))
        self.coupling_type_button.setItemText(1, QCoreApplication.translate("MainWindow", u"DC", None))

        self.eload_control.setTitle(QCoreApplication.translate("MainWindow", u"Eload", None))
        self.comms_box.setTitle(QCoreApplication.translate("MainWindow", u"Comms", None))
        self.comms_ac_button.setText(QCoreApplication.translate("MainWindow", u"Check connection", None))
        self.comms_eload_button.setText(QCoreApplication.translate("MainWindow", u"Check connection", None))
        self.ac_address_label.setText(QCoreApplication.translate("MainWindow", u"AC", None))
        self.comms_scope_button.setText(QCoreApplication.translate("MainWindow", u"Check connection", None))
        self.eload_address_label.setText(QCoreApplication.translate("MainWindow", u"Eload", None))
        self.scope_address_label.setText(QCoreApplication.translate("MainWindow", u"Scope", None))
        self.led_address_label.setText(QCoreApplication.translate("MainWindow", u"LED", None))
        self.comms_led_button.setText(QCoreApplication.translate("MainWindow", u"Check connection", None))
        self.scope_control.setTitle(QCoreApplication.translate("MainWindow", u"Scope Control", None))
        self.time_scale_label.setText(QCoreApplication.translate("MainWindow", u"TIME SCALE", None))
        self.time_scale_label_2.setText(QCoreApplication.translate("MainWindow", u"RECORD LENGTH", None))
        self.time_postion_label.setText(QCoreApplication.translate("MainWindow", u"TIME POSITION", None))
        self.trigger_type_combobox.setItemText(0, QCoreApplication.translate("MainWindow", u"Window", None))
        self.trigger_type_combobox.setItemText(1, QCoreApplication.translate("MainWindow", u"Edge", None))
        self.trigger_type_combobox.setItemText(2, QCoreApplication.translate("MainWindow", u"Timeout", None))

        self.filename_label.setText(QCoreApplication.translate("MainWindow", u"Filename", None))
        self.trigger_edge_combobox.setItemText(0, QCoreApplication.translate("MainWindow", u"EITH", None))
        self.trigger_edge_combobox.setItemText(1, QCoreApplication.translate("MainWindow", u"NEG", None))
        self.trigger_edge_combobox.setItemText(2, QCoreApplication.translate("MainWindow", u"POS", None))

        self.folder_path_label.setText(QCoreApplication.translate("MainWindow", u"Folder Path", None))
        self.scope_single_button.setText(QCoreApplication.translate("MainWindow", u"Single", None))
        self.screenshot_button.setText(QCoreApplication.translate("MainWindow", u"Screenshot", None))
        self.trigger_channel_combobox.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.trigger_channel_combobox.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.trigger_channel_combobox.setItemText(2, QCoreApplication.translate("MainWindow", u"3", None))
        self.trigger_channel_combobox.setItemText(3, QCoreApplication.translate("MainWindow", u"4", None))

        self.norm_button.setText(QCoreApplication.translate("MainWindow", u"NORM", None))
        self.scope_run_stop_button.setText(QCoreApplication.translate("MainWindow", u"Run\n"
"Stop", None))
        self.trigger_level_label.setText(QCoreApplication.translate("MainWindow", u"LEVEL", None))
        self.trigger_type_label.setText(QCoreApplication.translate("MainWindow", u"TRIGGER", None))
        self.trigger_channel_label.setText(QCoreApplication.translate("MainWindow", u"SOURCE", None))
        self.trigger_edge_label.setText(QCoreApplication.translate("MainWindow", u"SLOPE", None))
        self.foldername_label.setText(QCoreApplication.translate("MainWindow", u"Folder Name", None))
        self.auto_button.setText(QCoreApplication.translate("MainWindow", u"AUTO", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"s/div", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"MAX", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"V", None))
        self.setting.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ch_rel_y_label.setText(QCoreApplication.translate("MainWindow", u"rel_y", None))
        self.ch_rel_x_textbox.setText(QCoreApplication.translate("MainWindow", u"50", None))
        self.ch_offset_label.setText(QCoreApplication.translate("MainWindow", u"OFFSET", None))
        self.ch_offset_textbox.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.ch_coupling_label.setText(QCoreApplication.translate("MainWindow", u"COUP", None))
        self.ch_bandwidth_unit.setText(QCoreApplication.translate("MainWindow", u"MHz", None))
        self.ch_coupling_combobox.setItemText(0, QCoreApplication.translate("MainWindow", u"DC 1MOhms", None))
        self.ch_coupling_combobox.setItemText(1, QCoreApplication.translate("MainWindow", u"AC", None))
        self.ch_coupling_combobox.setItemText(2, QCoreApplication.translate("MainWindow", u"DC", None))

        self.scope_channel_1_enable_button.setText(QCoreApplication.translate("MainWindow", u"CH1", None))
        self.ch_rel_y_textbox.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.invert_button.setText(QCoreApplication.translate("MainWindow", u"INVERT", None))
        self.ch_color_combobox.setItemText(0, QCoreApplication.translate("MainWindow", u"YELLOW", None))
        self.ch_color_combobox.setItemText(1, QCoreApplication.translate("MainWindow", u"LIGHT_BLUE", None))
        self.ch_color_combobox.setItemText(2, QCoreApplication.translate("MainWindow", u"PINK", None))
        self.ch_color_combobox.setItemText(3, QCoreApplication.translate("MainWindow", u"GREEN", None))
        self.ch_color_combobox.setItemText(4, QCoreApplication.translate("MainWindow", u"BLUE", None))
        self.ch_color_combobox.setItemText(5, QCoreApplication.translate("MainWindow", u"ORANGE", None))

        self.ch_scale_textbox.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.ch_color_label.setText(QCoreApplication.translate("MainWindow", u"COLOR", None))
        self.ch_position_textbox.setText(QCoreApplication.translate("MainWindow", u"-4", None))
        self.ch_label_textbox.setText(QCoreApplication.translate("MainWindow", u"DRAIN VOLTAGE", None))
        self.ch_label_label.setText(QCoreApplication.translate("MainWindow", u"LABEL", None))
        self.ch_bandwidth_label.setText(QCoreApplication.translate("MainWindow", u"BW", None))
        self.autozero_button.setText(QCoreApplication.translate("MainWindow", u"AUTOZERO", None))
        self.ch_scale_label.setText(QCoreApplication.translate("MainWindow", u"SCALE", None))
        self.ch_rel_x_label.setText(QCoreApplication.translate("MainWindow", u"rel_x", None))
        self.ch_position_label.setText(QCoreApplication.translate("MainWindow", u"POS", None))
        self.ch_bandwidth_combobox.setItemText(0, QCoreApplication.translate("MainWindow", u"500", None))
        self.ch_bandwidth_combobox.setItemText(1, QCoreApplication.translate("MainWindow", u"200", None))
        self.ch_bandwidth_combobox.setItemText(2, QCoreApplication.translate("MainWindow", u"20", None))

        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Cursor 1", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"3", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"4", None))

        self.comboBox_2.setItemText(0, QCoreApplication.translate("MainWindow", u"Horizontal", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("MainWindow", u"Vertical", None))
        self.comboBox_2.setItemText(2, QCoreApplication.translate("MainWindow", u"Paired", None))

        self.label.setText(QCoreApplication.translate("MainWindow", u"X1", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"X2", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Y2", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Y1", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"CH", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Measure 1", None))
        self.ch_color_label_2.setText(QCoreApplication.translate("MainWindow", u"TYPE", None))
        self.ch_color_combobox_2.setItemText(0, QCoreApplication.translate("MainWindow", u"VOLTAGE", None))
        self.ch_color_combobox_2.setItemText(1, QCoreApplication.translate("MainWindow", u"CURRENT", None))

        self.label_6.setText(QCoreApplication.translate("MainWindow", u"V/div", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"div", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"V", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"START", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"END", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"SLEW", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"START", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"ABORT", None))
        self.eload_enable_button.setText(QCoreApplication.translate("MainWindow", u"ENABLE", None))
        self.eload_channel_label.setText(QCoreApplication.translate("MainWindow", u"CHANNEL", None))
        self.eload_mode_label.setText(QCoreApplication.translate("MainWindow", u"MODE", None))
        self.eload_iout_unit_label_1.setText(QCoreApplication.translate("MainWindow", u"mA", None))
        self.eload_iout_label.setText(QCoreApplication.translate("MainWindow", u"Iout", None))
        self.eload_iout_label_1.setText(QCoreApplication.translate("MainWindow", u"Iout", None))
        self.eload_iout_unit_label.setText(QCoreApplication.translate("MainWindow", u"mA", None))
        self.eload_channel_combobox.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.eload_channel_combobox.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.eload_channel_combobox.setItemText(2, QCoreApplication.translate("MainWindow", u"3", None))
        self.eload_channel_combobox.setItemText(3, QCoreApplication.translate("MainWindow", u"4", None))
        self.eload_channel_combobox.setItemText(4, QCoreApplication.translate("MainWindow", u"5", None))
        self.eload_channel_combobox.setItemText(5, QCoreApplication.translate("MainWindow", u"6", None))
        self.eload_channel_combobox.setItemText(6, QCoreApplication.translate("MainWindow", u"7", None))
        self.eload_channel_combobox.setItemText(7, QCoreApplication.translate("MainWindow", u"8", None))

        self.eload_mode_combobox.setItemText(0, QCoreApplication.translate("MainWindow", u"CCH", None))
        self.eload_mode_combobox.setItemText(1, QCoreApplication.translate("MainWindow", u"CCDH", None))
        self.eload_mode_combobox.setItemText(2, QCoreApplication.translate("MainWindow", u"CCDL", None))
        self.eload_mode_combobox.setItemText(3, QCoreApplication.translate("MainWindow", u"CRDH", None))
        self.eload_mode_combobox.setItemText(4, QCoreApplication.translate("MainWindow", u"CRDL", None))
        self.eload_mode_combobox.setItemText(5, QCoreApplication.translate("MainWindow", u"CCL", None))
        self.eload_mode_combobox.setItemText(6, QCoreApplication.translate("MainWindow", u"CRH", None))
        self.eload_mode_combobox.setItemText(7, QCoreApplication.translate("MainWindow", u"CRL", None))
        self.eload_mode_combobox.setItemText(8, QCoreApplication.translate("MainWindow", u"LEDH", None))
        self.eload_mode_combobox.setItemText(9, QCoreApplication.translate("MainWindow", u"LEDL", None))
        self.eload_mode_combobox.setItemText(10, QCoreApplication.translate("MainWindow", u"CV", None))

        self.label_15.setText(QCoreApplication.translate("MainWindow", u"E-LOAD TRANSIENT", None))
        self.eload_iout_unit_label_2.setText(QCoreApplication.translate("MainWindow", u"mA", None))
        self.eload_iout_unit_label_3.setText(QCoreApplication.translate("MainWindow", u"mA", None))
        self.eload_iout_unit_label_4.setText(QCoreApplication.translate("MainWindow", u"mA/s", None))
        self.measure_button.setText(QCoreApplication.translate("MainWindow", u"MEASURE", None))
    # retranslateUi

