# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'measurement_window_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(273, 212)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 131, 191))
        self.groupBox.setObjectName("groupBox")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_7.setGeometry(QtCore.QRect(10, 100, 70, 17))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_5.setGeometry(QtCore.QRect(10, 60, 91, 17))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 40, 70, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_6.setGeometry(QtCore.QRect(10, 80, 70, 17))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_16 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_16.setGeometry(QtCore.QRect(10, 160, 70, 17))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_15 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_15.setGeometry(QtCore.QRect(10, 140, 70, 17))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_14 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_14.setGeometry(QtCore.QRect(10, 120, 70, 17))
        self.checkBox_14.setObjectName("checkBox_14")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(150, 10, 111, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_8.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_17 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_17.setGeometry(QtCore.QRect(10, 140, 70, 17))
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_9.setGeometry(QtCore.QRect(10, 40, 70, 17))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_13.setGeometry(QtCore.QRect(10, 80, 70, 17))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_11.setGeometry(QtCore.QRect(10, 120, 70, 17))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_18 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_18.setGeometry(QtCore.QRect(10, 160, 70, 17))
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_10.setGeometry(QtCore.QRect(10, 100, 70, 17))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_12.setGeometry(QtCore.QRect(10, 60, 70, 17))
        self.checkBox_12.setObjectName("checkBox_12")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Amplitude Measurement"))
        self.checkBox_7.setText(_translate("Form", "Mean"))
        self.checkBox_5.setText(_translate("Form", "Peak-to-Peak"))
        self.checkBox_3.setText(_translate("Form", "Max"))
        self.checkBox_4.setText(_translate("Form", "Min"))
        self.checkBox_6.setText(_translate("Form", "RMS"))
        self.checkBox_16.setText(_translate("Form", "Amplitude"))
        self.checkBox_15.setText(_translate("Form", "Low"))
        self.checkBox_14.setText(_translate("Form", "High"))
        self.groupBox_2.setTitle(_translate("Form", "Time Measurement"))
        self.checkBox_8.setText(_translate("Form", "Frequency"))
        self.checkBox_17.setText(_translate("Form", "Pos. Pulse"))
        self.checkBox_9.setText(_translate("Form", "Period"))
        self.checkBox_13.setText(_translate("Form", "Fall Time"))
        self.checkBox_11.setText(_translate("Form", "Neg Duty"))
        self.checkBox_18.setText(_translate("Form", "Neg. Pulse"))
        self.checkBox_10.setText(_translate("Form", "Pos Duty"))
        self.checkBox_12.setText(_translate("Form", "Rise Time"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
